### ISSUE TITLE
Run "opcap version" without configuring access to a cluster

### ISSUE THREAD

**Issue by mgoerens** [opdev/opcap#120]
Currently one requires access to a OCP cluster to run `opcap version`. This shouldn't be necessary.

**Comment by mrhillsman** [comment]
Should I expect empty values?

Melvins-MacBook-Pro:opcap mrhillsman$ go run main.go version
I0727 09:20:00.341734   72412 request.go:601] Waited for 1.003606412s due to client-side throttling, not priority and fairness, request: GET:https://api.exedb-sno-pool-two-28zzw.opdev.io:6443/apis/operators.coreos.com/v1alpha1?timeout=32s
Version:         
Go Version:      
Build Time:      
Git User:        
Git Commit: 

@mgoerens
