### ISSUE TITLE
Expose deployment, and pod statuses in the reporting.

### ISSUE THREAD

**Issue by rocrisp** [opdev/opcap#122]
Here is an example of statuses we can expose. Right now, it's writing to the log.

{"level":"info","message":"failed","deploymentMessage":["Created new replica set \"runai-operator-56744fc4f6\"","Deployment does not have minimum availability.","pods \"runai-operator-56744fc4f6-\" is forbidden: error looking up service account opcap-installkit-customer/runai-operator: serviceaccount \"runai-operator\" not found"],"podmessage":[],"csvmessage":"install timeout","package":"installkit-customer","channel":"stable","installmode":"AllNamespaces"}

{"level":"info","message":"failed","podmessage":"containers with unready status: [manager]:containers with unready status: [manager]:Back-off pulling image \"registry.connect.redhat.com/rhm-labs/arcade-operator@sha256:d6959be6693728d2dc4cd38b69251551d23c5002cb52db2684df31a0a8f7b0ab\":","csvmessage":"install timeout","package":"marketplace-games-operator","channel":"alpha","installmode":"AllNamespaces"}

**Comment by acmenezes** [comment]
Hi @rocrisp, nice to see you here! I have a couple of questions:

- What exactly is the problem you're trying to solve with this data? Example: is this data for troubleshooting operators? Is this data to calculate statistics? Is this data to have a verbose tracing option for opcap? Is it to be used in reports? See that the audiences are different for each case?

- Another question is: how about moving those messages  to another `level` instead of `info` in the logs while we don't have a new reporting format? I may be wrong but the information you shared as an example looks more like a `debug` level to me.

**Comment by rocrisp** [comment]
Hi Alex, Thank you for taking the time to look at this one. 
So, the problem I see right now is we don't know why the operator failed to install.
The 12 operator I tested have different problems so by gathering these type of data we can begin to understand more about the operator install behavior. I think the data can be used in many ways, but right now, I'm focused on reporting. 
Hmm, it's not debug I think because the problem is with operator and cluster size in some cases. 
But, I think we can wait for the new report format to implement this features.
What do you think?

**Comment by acmenezes** [comment]
Hi @rocrisp , didn't hear from you for a while. I closing this one for now. Let me know if you would like to reopen when you're ready. I'll be glad to work with you on that.
