### ISSUE TITLE
Add functions and package for port-forwarding pods to local opcap environment

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#283]

**Comment by yashoza19** [comment]
@acmenezes As per our discussion today, We would like to make a suggestion to use certified-operator repository(https://github.com/redhat-openshift-ecosystem/certified-operators/tree/main/operators) to get a list of all the operators available and use that as part of opcap instead of using a catalog. Some more research is required to move forward.

**Comment by acmenezes** [comment]
@yashoza19 closing this one. Replaced gRPC completely with cloning the certified-operators.
