### ISSUE TITLE
Create an opcap debug mode report for failed or timed out operators

### ISSUE THREAD

**Issue by acmenezes** [opdev/opcap#331]
While troubleshooting operator installation, generally speaking, engineers will follow some steps like the ones below:
- check events
- check CSV status
- check installPlan status
- check operator's pod status
- check operator's CR status and conditions
- check for messages in OLM package server

The proposal here is to create a report as rich as possible that can be enabled for a short list of operators that are either failing or timing out in order to determine the cause of failure and gather data to approach the partner developer.

**Comment by acmenezes** [comment]
Include deprecated APIs:
- you may find errors on the controller logs. 
- check for RBAC permissions as well
- check OCP kube api version and check release notes
- check OCP api endpoints on release notes as well

**Comment by madorn** [comment]
@acmenezes: @yashoza19 and I were reviewing use of [ApiRequestCount API](https://docs.openshift.com/container-platform/4.11/rest_api/metadata_apis/apirequestcount-apiserver-openshift-io-v1.html).

It appears too unreliable due to the time it takes to populate with origin user account.

We were thinking we could tie into PR #334 and check installreport for `KubeAPIWarningLogger`. We did some testing and thsi should not only appear in controller logs when watching a deprecated endpoint, but will also appear on any CRUD function against API (i.e. after CR creation/operand install).
